#!/bin/sh

# Paths in project
ROOT=~

PROJECT_DIR=$ROOT/Projects/github/dotfiles 	# dotfiles github directory
DOTFILES_SHELL=$PROJECT_DIR/shell
BACKUP_DIR=$ROOT/Backup/dotfiles_backup     # old/existing dotfiles backup directory

# list of files/folders to symlink in homedir
DOTFILES_LIST="alias antigenrc"

# Logging helpers
WARN='\033[0;33m'
ERR='\033[0;31m'
OKEY='\033[0;32m'
GREY='\033[1;37m'
NC='\033[0m'

# Logging functions and variables
okey () { echo "\033[0;32m\xE2\x9C\x94\033[0m" | iconv -f UTF-8; }
wrn () { echo "${GREY}[${WARN}!${GREY}] ${1}${NC}"; }
err () { echo "${GREY}[${ERR}x${GREY}] ${1}${NC}"; }
info () { echo "${GREY}[i] ${1}${NC}"; }
msg () { echo "${1}"; }
date=$(date +"%Y%m%d%H%M%S")

# Question functionsS
ask () { printf "${GREY}[?] ${1} (y/n)${NC} "; }

# Utility functions
link () { ln -sFf "$1" "$2"; }

# Ask then take action function
askAndDo () {
  ask "$2"
  read -r option
  case "$option" in y|Y|yes|Yes )
    $1;
    return;;
  esac
}

itsDone () {
  msg "done"
}

tick () {
  echo "\xE2\x9C\x94" | iconv -f UTF-8
}
