#!/bin/sh

# import helpers
. "$(dirname "$0")"/helpers

SW_FOLDER=$ROOT/Software
ANTIGEN_FOLDER=$SW_FOLDER/Antigen/

installDependencies () {
  info "Updating CURL and MAKE dependencies locally (if / when prompted, enter password)"
  sudo apt-get -qq install -y libssl-dev autoconf libtool make zsh npm
}

installNode () {
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  nvm use 16
  npm install --global yarn
}

downloadAntigen () {
  info "Downloading Antigen"
  mkdir -p "$ANTIGEN_FOLDER"
  curl -sL http://git.io/antigen > "$ANTIGEN_FOLDER"/antigen.zsh
  okey
}

installOhMyZSH() {
  # Further installation options: https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH
  echo "Installing oh-my-zsh..."
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  sudo chsh -s "$(which zsh)" "$USER"
  exit
}

install_software () {
  installDependencies
  installNode
  installOhMyZSH
  downloadAntigen
}

askAndDo install_software "Install required software?"