#!/bin/sh

# import helpers
. "$(dirname "$0")"/helpers

SW_FOLDER=$ROOT/Software
ANTIGEN_FOLDER=$SW_FOLDER/Antigen/

installDependencies () {
  info "Updating CURL and MAKE dependencies locally (if / when prompted, enter password)"
  sudo apt-get -qq install -y libssl-dev autoconf libtool make zsh
}
downloadAntigen () {
  info "Downloading Antigen"
  mkdir -p "$ANTIGEN_FOLDER"
  curl -sL http://git.io/antigen > "$ANTIGEN_FOLDER"/antigen.zsh
  okey
}

installOhMyZSH() {
  # Further installation options: https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH
  echo "Installing oh-my-zsh..."
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  sudo chsh -s "$(which zsh)" "$USER"
  okey
}

install_software () {
  installDependencies
  installOhMyZSH
  downloadAntigen
}

askAndDo install_software "Install required software?"